{% set name = "wsinfer-zoo" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wsinfer_zoo-{{ version }}.tar.gz
  sha256: 12e73595e6c9e9013f9ae300db6ef2e64c429e481e0a4e5329fa34b6f006f3de

build:
  entry_points:
    - wsinfer-zoo = wsinfer_zoo.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - click >=8.0,<9,!=8.1.4,!=8.1.5
    - huggingface_hub
    - jsonschema
    - tabulate

test:
  imports:
    - wsinfer_zoo
  commands:
    - pip check
    - wsinfer-zoo --help
  requires:
    - pip

about:
  home: https://github.com/SBU-BMI/wsinfer-zoo
  summary: A client for model zoo for WSInfer-compatible models.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kaczmarj
